// Generated by scripts/vendor-aeronautics.mjs from anywidget-instruments-aeronautics fb3a477a434a7590d24bb629f8636f675982e6e9: widget classes and their _kind, from static/contract.json. Do not edit.
export const AERONAUTICS_KINDS: Record<string, string> = {
  "AirspeedIndicator": "awf-airspeed",
  "Altimeter": "awf-altimeter",
  "AttitudeIndicator": "awf-attitude",
  "HeadingIndicator": "awf-heading",
  "TurnCoordinator": "awf-turn",
  "VerticalSpeedIndicator": "awf-vsi"
};
