// Generated by scripts/vendor-automotive.mjs from anywidget-instruments-automotive dc2c98ca1b9b7e921fa5c6421854de35978f0f00: widget classes and their _kind, from static/contract.json. Do not edit.
export const AUTOMOTIVE_KINDS: Record<string, string> = {
  "Cluster": "awa-cluster",
  "FuelGauge": "awa-fuelgauge",
  "GearIndicator": "awa-gearindicator",
  "Odometer": "awa-odometer",
  "PowerFlow": "awa-powerflow",
  "PowerMeter": "awa-powermeter",
  "Speedometer": "awa-speedometer",
  "StateOfChargeGauge": "awa-stateofchargegauge",
  "Tachometer": "awa-tachometer",
  "TellTale": "awa-telltale",
  "TellTaleCluster": "awa-telltalecluster",
  "TemperatureGauge": "awa-temperaturegauge",
  "TripComputer": "awa-tripcomputer"
};
